### PR TITLE
Splash Screen Added

### LINKED ISSUE #2: Add Splash Screen
Screenshot 2021-02-12 at 3 31 15 PM

We need to show a screen similar to this to the user every time he opens the app.

### PR DESCRIPTION
**Pull request by hemangdtu**
# Description

Added splash screen to the flutter application and enhanced the project structure a bit.

## Screenshot
Splash Screen

### CODE REVIEW

**Comment by infiniteoverflow** [comment]
@hemangdtu , kindly remove all the extra files from the commit. There are 702 committed files. Just make a PR again with only the lib/ folder added to the commit as you are working only in that folder.

**Comment by hemangdtu** [comment]
Sir I have once again started to work on it.

**Comment by hemangdtu** [comment]
Please check the changes now. Sorry for the inconvenience caused.

**Comment by infiniteoverflow** [comment]
@hemangdtu Thats okay , it happens to anyone... 

I will go through the changes and get back.

**Comment by infiniteoverflow** [comment]
Looks great !! Good job.

**Comment by hemangdtu** [comment]
Thankyou @infiniteoverflow for giving me this opportunity.

**Comment by infiniteoverflow** [comment]
@hemangdtu Mention not, it's my duty. Keep up the good work ✨🌟

**Pull request merged**
